"""added_target_duration

Revision ID: 93ed72c1ecbd
Revises: cbf29a29e4ae
Create Date: 2026-05-25 10:03:36.192893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93ed72c1ecbd"
down_revision: Union[str, Sequence[str], None] = "cbf29a29e4ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("routine_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("target_duration_secs", sa.Integer(), nullable=True)
        )
        batch_op.alter_column("target_reps", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_workouts_routine_id",
            "routines",
            ["routine_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_workouts_routine_id", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "routines", ["routine_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("routine_items", schema=None) as batch_op:
        batch_op.alter_column("target_reps", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("target_duration_secs")

    # ### end Alembic commands ###
