export const equipmentOptions = [
  { value: "all", title: "All" },
  { value: "bodyweight", title: "Bodyweight" },
  { value: "cable", title: "Cable" },
  { value: "leveragemachine", title: "Leverage Machine" },
  { value: "assisted", title: "Assisted" },
  { value: "medicineball", title: "Medicine Ball" },
  { value: "barbell", title: "Barbell" },
  { value: "rope", title: "Rope" },
  { value: "stabilityball", title: "Stability Ball" },
  { value: "dumbbell", title: "Dumbbell" },
  { value: "ezbarbell", title: "EZ Barbell" },
  { value: "kettlebell", title: "Kettlebell" },
  { value: "olympicbarbell", title: "Olympic Barbell" },
  { value: "weighted", title: "Weighted" },
  { value: "bosuball", title: "BOSU Ball" },
  { value: "sledmachine", title: "Sled Machine" },
  { value: "smithmachine", title: "Smith Machine" },
  { value: "wheelroller", title: "Wheel Roller" },
  { value: "trapbar", title: "Trap Bar" },
  { value: "band", title: "Band" },
  { value: "hammer", title: "Hammer" },
  { value: "stationarybike", title: "Stationary Bike" },
  { value: "upperbodyergometer", title: "Upper Body Ergometer" },
  { value: "ellipticalmachine", title: "Elliptical Machine" },
  { value: "skiergmachine", title: "SkiErg Machine" },
  { value: "roller", title: "Roller" },
  { value: "stepmillmachine", title: "Stepmill Machine" },
  { value: "tire", title: "Tire" },
  { value: "resistanceband", title: "Resistance Band" },
];

export const muscleGroupOptions = [
  { value: "all", title: "All" },
  { value: "Abdominals", title: "Abdominals" },
  { value: "Ankles", title: "Ankles" },
  { value: "Back", title: "Back" },
  { value: "Biceps", title: "Biceps" },
  { value: "Calves", title: "Calves" },
  { value: "Chest", title: "Chest" },
  { value: "Core", title: "Core" },
  { value: "Deltoids", title: "Deltoids" },
  { value: "Forearms", title: "Forearms" },
  { value: "Glutes", title: "Glutes" },
  { value: "Grip Muscles", title: "Grip Muscles" },
  { value: "Groin", title: "Groin" },
  { value: "Hamstrings", title: "Hamstrings" },
  { value: "Hip Flexors", title: "Hip Flexors" },
  { value: "Inner Thighs", title: "Inner Thighs" },
  { value: "Lats", title: "Lats" },
  { value: "Lower Abs", title: "Lower Abs" },
  { value: "Lower Back", title: "Lower Back" },
  { value: "Obliques", title: "Obliques" },
  { value: "Quadriceps", title: "Quadriceps" },
  { value: "Rear Deltoids", title: "Rear Deltoids" },
  { value: "Rhomboids", title: "Rhomboids" },
  { value: "Rotator Cuff", title: "Rotator Cuff" },
  { value: "Shoulders", title: "Shoulders" },
  { value: "Traps", title: "Traps" },
  { value: "Triceps", title: "Triceps" },
  { value: "Upper Back", title: "Upper Back" },
  { value: "Upper Chest", title: "Upper Chest" },
  { value: "Wrists", title: "Wrists" },
];
